name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin

      - name: Set Git identity
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git config --global init.defaultBranch master

      - name: Setup build environment
        run: ./aero setup

      - name: Apply patches
        run: ./aero patch

      - name: Build
        uses: burrunan/gradle-cache-action@v3
        with:
          arguments: build paperclipJar
          read-only: false

      - name: Copy Paperclip jar
        run: |
          cp -v "./paperclip/build/libs/paperclip-1.8.8-R0.1-SNAPSHOT.jar" "./aerosmith-$GITHUB_RUN_NUMBER.jar"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Server JAR
          path: aerosmith-${{ github.run_number }}.jar
          if-no-files-found: error
